### ISSUE TITLE
calculate the accuracy

### ISSUE THREAD

**Issue by jijibn** [abhshkdz/neural-vqa-attention#2]
Hello,
 how can we calculate the accuracy at each checkpoint?

**Comment by abhshkdz** [comment]
[The readme](https://github.com/abhshkdz/neural-vqa-attention#running-evaluation) has instructions on how to generate answer predictions into a json file. To compute accuracy, you should use the [VQA evaluation tools](https://github.com/GT-Vision-Lab/VQA).
