### ISSUE TITLE
How did you create the attention maps in your readme?

### ISSUE THREAD

**Issue by Karol-G** [abhshkdz/neural-vqa-attention#3]
Hey,

in your readme you showed multiple attention maps. How did you create these? I don't mean which part of code you used but the method/technique in general?

Best,
Karol

**Comment by abhshkdz** [comment]
These are attention maps from SAN-1 (not sure if that answers your question.).

Code's here if that helps: https://github.com/abhshkdz/neural-vqa-attention/blob/master/attention_visualization.ipynb
